[package]
name = "os"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
rustsbi = { version = "0.4.0", features = ["forward", "machine"] }
sbi-rt = { version = "0.0.3", features = ["legacy"] }
